s = {1,5,32,54,5,5,5,"ZAIN"}

print(s,type(s))

1, s.add(566)
print(s,type(s))
2, s.clear()
print(s,type(s))
3, s.copy()
print(s,type(s))
s.remove(1)
4, print(s, type(s))

#properties of sets
# 1. sets are unordered => elements ordered doesn't matter
# 2. sets are unindexed => Cannot access elements by index
# 3. there is no way to change items in sets there is immutable
# 4. sets doesnot contain duplicate values
  

