a = int(input("Enter the number 1:")) # input function always takes string input so we convert it into integer using int()
b = int(input("Enter the number 2:")) # input function always takes string input so we convert it into integer using int()
print("number a is:", a)  # it will print the value of a 
print("number b is:", b) # it will print the value of b
print("The sum is:", a+b) # it will print the sum of a and b



