a = int(input("Enter Your Age: "))
# If elif else Ladder
if(a>=18):
    print("you are above the age of consent: ")
    print("Good for you")
elif(a<0): 
    print("you're entering a invalid  negative age")

elif(a==0):
    print("you're entering an invalid 0 age")



else:
    print("You are below the age of consent: ")

print("End of the program") 
   
a = int(input("ENTER YOUR AGE: "))
if(a>18):
    print("YOU'RE AGE OF CONSELT: ")
    print("you're a good boy")

elif(a<0):
    print("you're invalid a negative digit")

elif(a==0): 
    print("please enter a valid digit")

else:
    print("you are below of conselt")

print("end of the program")