# Create an empty dictionary. Allow 4 freinds to enter their favorite languages as value & use keys as their names 
# Assume that the names are unique
d = {}
name = input("Enter freinds name: ")
lang = input("Enter your favorite language: ")
d.update({name:lang})
print(d)
name = input("Enter freinds name: ")
lang = input("Enter your favorite language: ")
d.update({name:lang})
print(d)
name = input("Enter freinds name: ")
lang = input("Enter your favorite language: ")
d.update({name:lang})
print(d)
name = input("Enter freinds name: ")
lang = input("Enter your favorite language: ")
d.update({name:lang})
print(d)